package org.tor2.chat

import java.math.BigInteger

/**
 * Just enough ed25519 to turn a code into an onion address.
 *
 * Tor derives a service's public key by multiplying the base point by an
 * expanded secret *without* clamping it, which is the one primitive
 * lazysodium does not expose. Rather than depend on a native symbol that may
 * or may not resolve on a given phone — a failure that would be silent, and
 * would leave codes resolving nowhere — it is done here in plain arithmetic
 * and checked against addresses generated by the desktop client.
 *
 * Speed does not matter: this runs once per code.
 */
object Ed25519 {

    private val P: BigInteger = BigInteger.TWO.pow(255) - BigInteger.valueOf(19)
    private val D: BigInteger = BigInteger.valueOf(-121665)
        .multiply(BigInteger.valueOf(121666).modInverse(P)).mod(P)
    private val I: BigInteger = BigInteger.TWO
        .modPow((P - BigInteger.ONE) / BigInteger.valueOf(4), P)

    /** The standard base point. */
    private val BY: BigInteger = BigInteger.valueOf(4)
        .multiply(BigInteger.valueOf(5).modInverse(P)).mod(P)
    private val BX: BigInteger = recoverX(BY)
    private val B: Point = Point(BX, BY)

    private data class Point(val x: BigInteger, val y: BigInteger)

    private fun recoverX(y: BigInteger): BigInteger {
        val yy = y.multiply(y).mod(P)
        val u = (yy - BigInteger.ONE).mod(P)
        val v = (D.multiply(yy) + BigInteger.ONE).mod(P)
        var x = u.multiply(v.modPow(BigInteger.valueOf(3), P))
            .multiply(
                u.multiply(v.modPow(BigInteger.valueOf(7), P))
                    .modPow((P - BigInteger.valueOf(5)) / BigInteger.valueOf(8), P))
            .mod(P)
        if (v.multiply(x).multiply(x).subtract(u).mod(P).signum() != 0) {
            x = x.multiply(I).mod(P)
        }
        if (x.testBit(0)) x = P.subtract(x)
        return x
    }

    private fun add(a: Point, b: Point): Point {
        val xx = a.x.multiply(b.x).mod(P)
        val yy = a.y.multiply(b.y).mod(P)
        val dxy = D.multiply(xx).multiply(yy).mod(P)
        val x = a.x.multiply(b.y).add(b.x.multiply(a.y))
            .multiply(BigInteger.ONE.add(dxy).modInverse(P)).mod(P)
        val y = a.y.multiply(b.y).add(xx)
            .multiply(BigInteger.ONE.subtract(dxy).mod(P).modInverse(P)).mod(P)
        return Point(x, y)
    }

    private fun scalarMultBase(scalar: BigInteger): Point {
        var result = Point(BigInteger.ZERO, BigInteger.ONE)   // neutral element
        var addend = B
        var k = scalar
        while (k.signum() > 0) {
            if (k.testBit(0)) result = add(result, addend)
            addend = add(addend, addend)
            k = k.shiftRight(1)
        }
        return result
    }

    private fun encode(p: Point): ByteArray {
        val out = ByteArray(32)
        val y = p.y.toByteArray().reversedArray()          // little endian
        System.arraycopy(y, 0, out, 0, minOf(y.size, 32))
        out[31] = (out[31].toInt() and 0x7f).toByte()
        if (p.x.testBit(0)) out[31] = (out[31].toInt() or 0x80).toByte()
        return out
    }

    /**
     * The public key for an already-expanded secret, with no clamping — what
     * tor does for onion service keys.
     */
    fun publicKeyNoClamp(expanded32: ByteArray): ByteArray {
        require(expanded32.size >= 32) { "need 32 bytes of scalar" }
        val little = expanded32.copyOfRange(0, 32).reversedArray()
        val scalar = BigInteger(1, little)
        return encode(scalarMultBase(scalar))
    }
}
